version: "3"
services:
  mongo:
     image: mongo 
     ports:
       - 27017:27017

  executor:  
    build: ./AionSystem
    depends_on: 
      - mongo
      - ganache
    environment: 
      - GANACHE=goalzapp_ganache_1
    labels: 
      purpose: "run the Aion system executor"
      platform: "node.js"

  truffle: 
    build: .
    depends_on:
      - ganache
    environment:
      LANG: en_US.UTF-8
      FORCE_COLOR: 'true'
    labels: 
      purpose: "run the GoalZapp test suite"
      platform: "node.js"
      framework: "truffle"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  
  ganache: 
    image: trufflesuite/ganache-cli:latest 
    command: ganache-cli  -e 1000 --allowUnlimitedContractSize -l 9007199254740991 -m "onion source advice ahead august giggle chaos friend photo all flame gallery"
    ports:
      - 8545:8545
    tty: true
    stdin_open: true
    labels: 
      purpose: "run the virtual ethereum network for testing, hosting Aion contract"
      platform: "node.js"
       
